# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2023-05-10 09:46:09 UTC
from __future__ import unicode_literals
import datetime

version = "3.1"
githash = "a6f2722357ade0eef2a6c1628bc183daa51f110c"


major = 3
minor = 1
bugfix = 0

version_info = (major, minor, bugfix)

release = True
timestamp = datetime.datetime(2023, 5, 10, 9, 46, 9)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
